name: Production CI

on: [push]

jobs:
  test:
    name: Test, Build & Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # # - name: BlueBase
      # #   uses: ./.github/actions/bluebase
      # #   with:
      # #     args: plugins:add @bluebase/cli-web
      # - name: Install Dependencies
      #   uses: Borales/actions-yarn@master
      #   with:
      #     args: install
      # # - name: Jest
      # #   uses: docker://rkusa/jest-action:latest
      # #   env:
      # #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # #   with:
      # #     args: --coverage --logHeapUsage
      # - name: Unit Tests (Jest)
      #   uses: Borales/actions-yarn@master
      #   with:
      #     args: test:only --coverage --logHeapUsage --ci
      # - name: Test Lint
      #   uses: Borales/actions-yarn@master
      #   with:
      #     args: test:lint
      # - name: Test Prettier
      #   uses: Borales/actions-yarn@master
      #   with:
      #     args: test:prettier
      # - name: Build
      #   uses: Borales/actions-yarn@master
      #   with:
      #     args: build
      # - name: Semantic Release
      #   run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  web-deploy:
    name: Deploy Web
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        uses: Borales/actions-yarn@master
        with:
          args: install

      - name: Install BlueBase Web Plugin
        uses: ./.github/actions/bluebase
        with:
          args: plugins:add @bluebase/cli-web

      - name: Build Web
        uses: ./.github/actions/bluebase
        with:
          args: web:build --static

      - name: Deploy To Now
        uses: ./.github/actions/now-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOW_TOKEN: ${{ secrets.ZEIT_TOKEN }}

  expo-publish:
    name: Expo Publish
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        uses: Borales/actions-yarn@master
        with:
          args: install

      - name: Install BlueBase Expo Plugin
        uses: ./.github/actions/bluebase
        with:
          args: plugins:add @bluebase/cli-expo

      - name: Build Expo
        uses: ./.github/actions/bluebase
        with:
          args: expo:build

      - name: Increase watchers
        run: |
          echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Publish on Expo
        uses: expo/expo-github-action@3.0.0
        with:
          args: publish --config=./build/expo/app.json
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

  expo-build-android:
    name: Expo BUild Android
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        uses: Borales/actions-yarn@master
        with:
          args: install

      - name: Install BlueBase Expo Plugin
        uses: ./.github/actions/bluebase
        with:
          args: plugins:add @bluebase/cli-expo

      - name: Build Expo
        uses: ./.github/actions/bluebase
        with:
          args: expo:build

      - name: Increase watchers
        run: |
          echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Publish on Expo
        uses: expo/expo-github-action@3.0.0
        with:
          args: build:android --config=./build/expo/app.json
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

  deploy-docs:
    name: Deploy Docs
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      # - name: Check if Master
      #   uses: actions/bin/filter@master
      #   with:
      #     args: branch master

      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: Borales/actions-yarn@master
        with:
          args: install

      - name: Build Docs
        uses: Borales/actions-yarn@master
        with:
          args: doc

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
      # - name: Deploy
      #   uses: maxheld83/ghpages@v0.2.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BUILD_DIR: 'docs'
